apiVersion: v1
kind: Service
metadata:
  name: z-react-redis-service
spec:
  selector:
    app: z-react-redis
  ports:
    - name: http
      protocol: TCP
      port: 5400
      targetPort: 5400
      nodePort: 30103
  type: LoadBalancer